# Generated by Django 4.2.4 on 2023-08-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_student_trainer_alter_trainer_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer',
            new_name='Trainer',
        ),
    ]
