# Generated by Django 4.2.4 on 2023-09-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_trainer_trainer_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
