# Generated by Django 4.2.4 on 2023-10-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_master_data_rename_batch_batch_batch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branche',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='Branche',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branche',
            new_name='branch',
        ),
    ]
